# ----------------------------------------------------------------------------------------------------------------------
# rustfmt : v1.4.18
# ----------------------------------------------------------------------------------------------------------------------
unstable_features = true                                   # true, *false
edition = "2018"                                           # *"2015", "2018"

# ----------------------------------------------------------------------------------------------------------------------
# Stable options
# ----------------------------------------------------------------------------------------------------------------------
# fn_args_layout = "Tall"                                    # "Compressed", *"Tall", "Vertical"
# force_explicit_abi = true                                  # *true, false
# hard_tabs = false                                          # true, *false
max_width = 120                                            # *100
# merge_derives = true                                       # *true, false
# newline_style = "Auto"                                     # *"Auto", "Native", "Unix", "Windows"
# remove_nested_parens = true                                # *true, false
# reorder_imports = true                                     # *true, false
# reorder_modules = true                                     # *true, false
tab_spaces = 2                                             # *4
use_field_init_shorthand = true                            # true, *false
# use_small_heuristics = "Default"                           # *"Default", "Off", "Max"
# use_try_shorthand = false                                  # true, *false

# ----------------------------------------------------------------------------------------------------------------------
# Unstable options
# ----------------------------------------------------------------------------------------------------------------------
binop_separator = "Back"                                   # *"Front", "Back"
# blank_lines_lower_bound = 0                                # *0
# blank_lines_upper_bound = 1                                # *1
# brace_style = "PreferSameLine"                             # "AlwaysNextLine", "PreferSameLine", *"SameLineWhere"
# color = "Auto"                                             # *"Auto", "Always", "Never"
# combine_control_expr = true                                # *true, false
# comment_width = 120                                        # *80
# condense_wildcard_suffixes = false                         # true, *false
# control_brace_style = "ClosingNextLine"                    # "AlwaysNextLine", "AlwaysSameLine", "ClosingNextLine"
# disable_all_formatting = false                             # true, *false
# empty_item_single_line = true                              # *true, false
# enum_discrim_align_threshold = 20                          # *0
# error_on_line_overflow = false                             # true, *false
# error_on_unformatted = false                               # true, *false
# fn_single_line = true                                      # *true, false
# force_multiline_blocks = false                             # true, *false
# format_code_in_doc_comments = true                         # true, *false
# format_macro_matchers = false                              # true, *false
# format_macro_bodies = true                                 # *true, false
# format_strings = true                                      # true, *false
# hide_parse_errors = false                                  # true, *false
# #ignore = [ "examples" ]                                    # Default formats every file. Use .gitignore patterns
# imports_indent = "Block"                                   # *"Block", "Visual"
# imports_layout = "HorizontalVertical"                      # "Horizontal", "HorizontalVertical", *"Mixed", "Vertical"
# indent_style = "Visual"                                    # *"Block", "Visual"
# inline_attribute_width = 0                                 # *0
# license_template_path = ""                                 # *""  Provide pathname to license template text file
# match_arm_blocks = true                                    # *true, false
# match_block_trailing_comma = false                         # true, *false
# merge_imports = true                                       # true, *false
# normalize_comments = false                                 # true, *false
# normalize_doc_attributes = false                           # true, *false
# overflow_delimited_expr = false                            # true, *false
# reorder_impl_items = true                                  # true, *false
# report_fixme = "Never"                                     # "Always", "Unnumbered", *"Never"
# report_todo = "Never"                                      # "Always", "Unnumbered", *"Never"
# required_version = "1.4.20"                                # *CARGO_PKG_VERSION
# skip_children = false                                      # true, *false
# space_after_colon = true                                   # *true, false
# space_before_colon = false                                 # true, *false
# spaces_around_ranges = false                               # true, *false
# struct_field_align_threshold = 20                          # *0
# struct_lit_single_line = true                              # *true, false
# trailing_comma = "Never"                                   # "Always", "Never", *"Vertical"
# trailing_semicolon = true                                  # *true, false
# type_punctuation_density = "Wide"                          # "Compressed", *"Wide"
# version = "One"                                            # *"One", "Two"
# where_single_line = false                                  # true, *false
# wrap_comments = true                                       # true, *false
